# Build settings
markdown: redcarpet
encoding: utf-8
highlighter: pygments

paginate: 5

url: "http://www.amightyo.tk"
baseurl: ""
exclude: ['README.md']

gallerytag:
    source_dir: img
    destination_dir: img/thumbs
    thumb_width: 150
    thumb_height: 150
    columns: 4                     # set to 0 and a <ul> list will be generated
    custom_attribute_name: data-lightbox

gems:
  - jekyll-mentions